# Personal Finance Classifier Configurations
title = "PersFin Configurations"

[paths]
column_mapper = "./configs/column_mapper_ABN_AMRO.toml"
classifiers = "./classifiers/NL"
output_files = "./outputs"
master_data = "./master_data"

[preprocess]
enabled = true
column = "Date"
script = "./utils/preprocesser/amro_date_preprocess.py"
