# Personal Finance Classifier Configurations
title = "PersFin Configurations"

[paths]
column_mapper = "./configs/canonical_schema_abn_amro.toml"
classifiers = "./classifiers/NL"
output_files = "./outputs"

[custom_preprocess]
enabled = true
column = "Date"
script = "amro_date_preprocess"

[classifiers]
"Groceries" = "groceries.json"
"Eating Out" = "eat_out.json"
"Cosmetics OOT Medicines" = "cosmetics_out_of_counter_medicines.json"
